trigger:
  - main

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: JonatanPache/dde_final_project
      ref: refs/heads/main
      endpoint: github.com_JonatanPache

variables:
  dockerRegistryServiceConnection: '8920e824-71a4-4bb8-bfe1-24a5b7f16cdb'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:
    - checkout: githubRepo

    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: 'puzzleContainer'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy to VM via Docker Compose
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: Default
    steps:
    - checkout: githubRepo

    - script: |
        ssh -o StrictHostKeyChecking=no azureuser@48.216.243.186 << 'EOF'
          cd ~/proypuzzle/dde_final_project
          docker-compose down -v --remove-orphans
          docker-compose stop app
          docker-compose rm -f app
          docker-compose up -d --build app
        EOF

      displayName: 'Deploy to VM using Docker Compose'